### ISSUE TITLE
How to make FileSystem work with directory?

### ISSUE THREAD

**Issue by buckle2000** [DeedleFake/Go-PhysicsFS#1]
http.Server is not working at all.

**Comment by DeedleFake** [comment]
Ah, sorry about that. This repo isn't particularly maintained anymore, at least in part because, thanks to the zip and tar support in the standard library, I've never really had a reason to use it.

**Comment by DeedleFake** [comment]
That being said, I've been intending for a while now to write a pure-Go variant of PhysicsFS. Maybe I'll finally get around to that.
